name: Build and Deploy to Render

on:
  push:
    branches:
      - main  # Trigger on push to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven

      - name: Build project with Maven
        run: mvn clean package

      - name: Build Docker image
        run: docker build -t hungvo2003vn/online-examination:latest .

      - name: Push Docker image to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push hungvo2003vn/online-examination:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Render
        run: |
          # Example using Render CLI (requires CLI installation)
          # render deploy service --service-id <YOUR_SERVICE_ID> --image hungvo2003vn/online-examination:latest
          
          # OR use the Render API:
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d '{
              "serviceId": "<YOUR_SERVICE_ID>",
              "image": "docker.io/hungvo2003vn/online-examination:latest"
            }' \
            https://api.render.com/v1/services/deploys
